In [1]:
l1 = [1,2,3,4,5]

In [2]:
# [1, 4, 9, 15, 25]

In [3]:
l2 = []
for i in l1:
    l2.append(i**2)

In [4]:
l2

[1, 4, 9, 16, 25]

In [5]:
l3 = [i**2 for i in l1]

In [6]:
l3

[1, 4, 9, 16, 25]

In [7]:
# loc and iloc

In [8]:
import pandas as pd

In [9]:
s1 = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])

In [10]:
s1

a    10
b    20
c    30
d    40
dtype: int64

In [11]:
s1.iloc[0]

10

In [12]:
s1.loc['a']

10

In [13]:
s1.iloc['b']

TypeError: Cannot index by location index with a non-integer key

In [14]:
import numpy as np

In [15]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
sorted_row = np.sort(A,axis=1)
sorted_col = np.sort(A,axis=0)
print("Sorted by row: \n",sorted_row)
print("Sorted by col.: \n",sorted_col)


Sorted by row: 
 [[ 3.49  4.99  9.99]
 [ 1.99  4.99  9.99]
 [ 2.39  7.29 14.99]]
Sorted by col.: 
 [[ 1.99  2.39  4.99]
 [ 4.99  3.49  7.29]
 [14.99  9.99  9.99]]


In [16]:
help(np.sort)

Help on function sort in module numpy:

sort(a, axis=-1, kind=None, order=None)
    Return a sorted copy of an array.
    
    Parameters
    ----------
    a : array_like
        Array to be sorted.
    axis : int or None, optional
        Axis along which to sort. If None, the array is flattened before
        sorting. The default is -1, which sorts along the last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort or radix sort under the covers and, in general,
        the actual implementation will vary with data type. The 'mergesort' option
        is retained for backwards compatibility.
    
        .. versionchanged:: 1.15.0.
           The 'stable' option was added.
    
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second, etc.  A si

In [17]:
# Generate a two-dimensional array _(200, 300)_ filled with random values from 0 to 255 (inclusive) 
# with data type _np.uint8_ and assign to the variable _image_.


In [18]:
image = np.random.randint(0, 256, (200, 300), dtype=np.uint8)

In [19]:
image

array([[ 86, 138, 135, ..., 255, 212, 174],
       [233, 191, 122, ...,   3, 220,  64],
       [ 18, 166, 177, ..., 114, 191, 121],
       ...,
       [148, 176,  64, ..., 196, 111,  84],
       [192, 116, 205, ..., 203,  84, 107],
       [167,  69, 147, ..., 115, 170, 123]], dtype=uint8)

In [20]:
# Then run the following block of code. 
# As a result, you'll get a preview of the randomly generated black and white image.


In [21]:
from google.colab.patches import cv2_imshow

cv2_imshow(image)

ModuleNotFoundError: No module named 'google'

In [22]:
!pip install google