In [1]:
import numpy as np

In [2]:
# Concatination of arrays

In [3]:
arr1 = np.random.randint(0, 10, (2, 3))
arr2 = np.random.randint(0, 10, (2, 3))

In [4]:
arr1

array([[9, 3, 6],
       [5, 6, 3]])

In [5]:
arr2

array([[1, 2, 5],
       [4, 5, 6]])

In [7]:
np.concatenate([arr1, arr2], axis=0)

array([[9, 3, 6],
       [5, 6, 3],
       [1, 2, 5],
       [4, 5, 6]])

In [8]:
np.concatenate([arr1, arr2], axis=1)

array([[9, 3, 6, 1, 2, 5],
       [5, 6, 3, 4, 5, 6]])

In [9]:
arr3 = np.random.randint(0, 10, (3, 3))

In [10]:
arr3

array([[5, 8, 8],
       [3, 1, 8],
       [7, 3, 7]])

In [11]:
arr1

array([[9, 3, 6],
       [5, 6, 3]])

In [12]:
np.concatenate([arr1, arr3], axis=0)

array([[9, 3, 6],
       [5, 6, 3],
       [5, 8, 8],
       [3, 1, 8],
       [7, 3, 7]])

In [13]:
np.concatenate([arr1, arr3], axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

In [14]:
# For axis = 0, the number of columns of both arrays should be same
# For axis = 1, the number of rows of both arrays should be same

In [15]:
# Splitting of arrays

In [16]:
arr4 = np.random.randint(0, 10, (10,))

In [17]:
arr4

array([7, 7, 1, 0, 4, 2, 2, 5, 9, 3])

In [18]:
np.split(arr4, 2)

[array([7, 7, 1, 0, 4]), array([2, 2, 5, 9, 3])]

In [19]:
np.split(arr4, 3)

ValueError: array split does not result in an equal division

In [20]:
np.split(arr4, 5)

[array([7, 7]), array([1, 0]), array([4, 2]), array([2, 5]), array([9, 3])]

In [21]:
arr4

array([7, 7, 1, 0, 4, 2, 2, 5, 9, 3])

In [22]:
# array_split

In [23]:
np.array_split(arr4, 3)

[array([7, 7, 1, 0]), array([4, 2, 2]), array([5, 9, 3])]

In [24]:
help(np.array_split)

Help on function array_split in module numpy:

array_split(ary, indices_or_sections, axis=0)
    Split an array into multiple sub-arrays.
    
    Please refer to the ``split`` documentation.  The only difference
    between these functions is that ``array_split`` allows
    `indices_or_sections` to be an integer that does *not* equally
    divide the axis. For an array of length l that should be split
    into n sections, it returns l % n sub-arrays of size l//n + 1
    and the rest of size l//n.
    
    See Also
    --------
    split : Split array into multiple sub-arrays of equal size.
    
    Examples
    --------
    >>> x = np.arange(8.0)
    >>> np.array_split(x, 3)
    [array([0.,  1.,  2.]), array([3.,  4.,  5.]), array([6.,  7.])]
    
    >>> x = np.arange(9)
    >>> np.array_split(x, 4)
    [array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]



In [25]:
# For an array of length l that should be split
#     into n sections, it returns l % n sub-arrays of size l//n + 1
#     and the rest of size l//n.

In [26]:
arr4

array([7, 7, 1, 0, 4, 2, 2, 5, 9, 3])

In [27]:
# l = 10
# n = 3

# 10 % 3 sub-arrays of size 10//3 + 1 => 1 sub array of size 3 + 1 = 4
# rest of the arrays (3-1 = 2) of size 10//3 = 2 sub arrays of size 3

In [28]:
np.array_split(arr4, 3)

[array([7, 7, 1, 0]), array([4, 2, 2]), array([5, 9, 3])]

In [29]:
arr5 = np.random.randint(0, 10, (13,))

In [30]:
arr5

array([3, 0, 3, 3, 8, 5, 1, 1, 2, 7, 6, 6, 4])

In [31]:
np.array_split(arr5, 3)

# l = 13
# n = 3

# 13 % 3 sub-arrays of size 13//3 + 1 => 1 sub array of size 4 + 1 = 5
# rest of the arrays (3-1 = 2) of size 13//3 = 2 sub arrays of size 4

[array([3, 0, 3, 3, 8]), array([5, 1, 1, 2]), array([7, 6, 6, 4])]