In [1]:
import numpy as np

In [2]:
l2 = [[1,2,3], [4,5,6]]

In [3]:
l2

[[1, 2, 3], [4, 5, 6]]

In [4]:
type(l2)

list

In [5]:
arr2 = np.array(l2)

In [6]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [9]:
print(l2)

[[1, 2, 3], [4, 5, 6]]


In [10]:
type(arr2)

numpy.ndarray

In [11]:
arr2.ndim

2

In [12]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
arr2.size

6

In [14]:
len(arr2)

2

In [15]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [16]:
arr2.dtype

dtype('int32')

In [17]:
# shape

In [18]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr2.shape

(2, 3)

In [20]:
a1 = [[1,2,3], [6, 9]]

In [21]:
a1

[[1, 2, 3], [6, 9]]

In [22]:
a2 = np.array(a1)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [23]:
arr3 = np.array([[[1,2], [3,4], [5,6]], [[7,8], [9, 0], [1,2]]])

In [24]:
arr3

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[7, 8],
        [9, 0],
        [1, 2]]])

In [25]:
print(arr3)

[[[1 2]
  [3 4]
  [5 6]]

 [[7 8]
  [9 0]
  [1 2]]]


In [26]:
arr3.ndim

3

In [27]:
arr3.size

12

In [28]:
arr3.shape

(2, 3, 2)

In [29]:
arr3.dtype

dtype('int32')

In [30]:
l1 = [1,2,3,4,5]

In [31]:
arr1 = np.array(l1)

In [32]:
arr1

array([1, 2, 3, 4, 5])

In [33]:
arr1.ndim

1

In [34]:
arr1.shape

(5,)

In [35]:
t1 = (5)

In [36]:
t1

5

In [37]:
type(t1)

int

In [38]:
t2 = (5,)

In [39]:
t2

(5,)

In [40]:
type(t2)

tuple

In [42]:
# Lists vs Arrays

In [43]:
l1

[1, 2, 3, 4, 5]

In [44]:
arr1

array([1, 2, 3, 4, 5])

In [45]:
type(l1)

list

In [46]:
type(arr1)

numpy.ndarray

In [47]:
l1

[1, 2, 3, 4, 5]

In [48]:
l1 + 10

TypeError: can only concatenate list (not "int") to list

In [49]:
[1,2] + [10, 20, 30]

[1, 2, 10, 20, 30]

In [50]:
arr1

array([1, 2, 3, 4, 5])

In [51]:
arr1 + 10

array([11, 12, 13, 14, 15])

In [52]:
l1

[1, 2, 3, 4, 5]

In [53]:
arr1

array([1, 2, 3, 4, 5])

In [54]:
np.array(l1) + 10

array([11, 12, 13, 14, 15])

In [55]:
list(np.array(l1) + 10)

[11, 12, 13, 14, 15]

In [56]:
arr1

array([1, 2, 3, 4, 5])

In [57]:
arr1 * 2

array([ 2,  4,  6,  8, 10])

In [60]:
arr1 / 3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [61]:
arr1 // 3

array([0, 0, 1, 1, 1], dtype=int32)

In [62]:
arr1

array([1, 2, 3, 4, 5])

In [64]:
out = arr1 % 2 == 0

In [65]:
out

array([False,  True, False,  True, False])

In [66]:
out.dtype

dtype('bool')

In [67]:
arr1

array([1, 2, 3, 4, 5])

In [68]:
arr1 > 3

array([False, False, False,  True,  True])

In [69]:
arr1 or 1

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [70]:
# arange

In [71]:
a1 = np.arange(10, 20, 3)

In [72]:
a1

array([10, 13, 16, 19])

In [73]:
list(range(10,20,3))

[10, 13, 16, 19]

In [74]:
range(2, 5, 0.5)

TypeError: 'float' object cannot be interpreted as an integer

In [75]:
a1 = np.arange(2, 5, 0.5)

In [76]:
a1

array([2. , 2.5, 3. , 3.5, 4. , 4.5])

In [77]:
a1.dtype

dtype('float64')

In [78]:
np.arange(10, 5, -1)

array([10,  9,  8,  7,  6])

In [79]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    ``arange`` can be called with a varying number of positional arguments:
    
    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.
    
    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.
    
    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.
    
    S

In [80]:
np.arange("2024-03-01", "2024-03-31")

TypeError: arange() not supported for inputs with DType <class 'numpy.dtype[str_]'>.

In [81]:
np.arange("2024-03-01", "2024-03-31", dtype='datetime64[D]')

array(['2024-03-01', '2024-03-02', '2024-03-03', '2024-03-04',
       '2024-03-05', '2024-03-06', '2024-03-07', '2024-03-08',
       '2024-03-09', '2024-03-10', '2024-03-11', '2024-03-12',
       '2024-03-13', '2024-03-14', '2024-03-15', '2024-03-16',
       '2024-03-17', '2024-03-18', '2024-03-19', '2024-03-20',
       '2024-03-21', '2024-03-22', '2024-03-23', '2024-03-24',
       '2024-03-25', '2024-03-26', '2024-03-27', '2024-03-28',
       '2024-03-29', '2024-03-30'], dtype='datetime64[D]')

In [82]:
np.arange("2024-03-01", "2024-03-32", dtype='datetime64[D]')

ValueError: Day out of range in datetime string "2024-03-32"

In [83]:
np.arange("2024-03-01", "2024-04-01", dtype='datetime64[D]')

array(['2024-03-01', '2024-03-02', '2024-03-03', '2024-03-04',
       '2024-03-05', '2024-03-06', '2024-03-07', '2024-03-08',
       '2024-03-09', '2024-03-10', '2024-03-11', '2024-03-12',
       '2024-03-13', '2024-03-14', '2024-03-15', '2024-03-16',
       '2024-03-17', '2024-03-18', '2024-03-19', '2024-03-20',
       '2024-03-21', '2024-03-22', '2024-03-23', '2024-03-24',
       '2024-03-25', '2024-03-26', '2024-03-27', '2024-03-28',
       '2024-03-29', '2024-03-30', '2024-03-31'], dtype='datetime64[D]')

In [84]:
np.arange("2024-03-01", "2024-06-01", 7, dtype='datetime64[D]')

array(['2024-03-01', '2024-03-08', '2024-03-15', '2024-03-22',
       '2024-03-29', '2024-04-05', '2024-04-12', '2024-04-19',
       '2024-04-26', '2024-05-03', '2024-05-10', '2024-05-17',
       '2024-05-24', '2024-05-31'], dtype='datetime64[D]')

In [86]:
np.arange("2024-03-01", "2024-06-01", 1, dtype='datetime64[M]')

array(['2024-03', '2024-04', '2024-05'], dtype='datetime64[M]')

In [87]:
np.arange("2024-03-01", "2024-06-01", 1, dtype='datetime64[W]')

array(['2024-02-29', '2024-03-07', '2024-03-14', '2024-03-21',
       '2024-03-28', '2024-04-04', '2024-04-11', '2024-04-18',
       '2024-04-25', '2024-05-02', '2024-05-09', '2024-05-16',
       '2024-05-23'], dtype='datetime64[W]')

In [88]:
np.arange("2024-03-02", "2024-06-01", 1, dtype='datetime64[W]')

array(['2024-02-29', '2024-03-07', '2024-03-14', '2024-03-21',
       '2024-03-28', '2024-04-04', '2024-04-11', '2024-04-18',
       '2024-04-25', '2024-05-02', '2024-05-09', '2024-05-16',
       '2024-05-23'], dtype='datetime64[W]')

In [92]:
np.arange("2024-03-07", "2024-06-01", 1, dtype='datetime64[W]')

array(['2024-03-07', '2024-03-14', '2024-03-21', '2024-03-28',
       '2024-04-04', '2024-04-11', '2024-04-18', '2024-04-25',
       '2024-05-02', '2024-05-09', '2024-05-16', '2024-05-23'],
      dtype='datetime64[W]')

In [94]:
np.arange("2023-03-01", "2023-06-01", dtype='datetime64[W]')

array(['2023-02-23', '2023-03-02', '2023-03-09', '2023-03-16',
       '2023-03-23', '2023-03-30', '2023-04-06', '2023-04-13',
       '2023-04-20', '2023-04-27', '2023-05-04', '2023-05-11',
       '2023-05-18', '2023-05-25'], dtype='datetime64[W]')

In [95]:
np.arange("2023-03-01", "2025-06-01", dtype='datetime64[M]')

array(['2023-03', '2023-04', '2023-05', '2023-06', '2023-07', '2023-08',
       '2023-09', '2023-10', '2023-11', '2023-12', '2024-01', '2024-02',
       '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08',
       '2024-09', '2024-10', '2024-11', '2024-12', '2025-01', '2025-02',
       '2025-03', '2025-04', '2025-05'], dtype='datetime64[M]')

In [96]:
np.arange("2023-03-01", "2025-06-01", dtype='datetime64[M]', roll='forward')

TypeError: arange() got an unexpected keyword argument 'roll'

In [97]:
# random package

In [98]:
# randint

In [99]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the `~numpy.random.Generator.randint`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to

In [100]:
np.random.randint(10, 30, (10,))

array([26, 27, 15, 29, 15, 25, 10, 20, 27, 13])

In [101]:
np.random.randint(10, 30, (10,))

array([25, 20, 22, 13, 21, 12, 25, 15, 29, 26])

In [102]:
np.random.randint(1, 9, (3, 4))

array([[7, 2, 1, 8],
       [8, 6, 2, 3],
       [4, 7, 3, 6]])

In [103]:
np.random.randint(1, 9, (3, 2, 4))

array([[[8, 4, 5, 3],
        [5, 5, 3, 8]],

       [[5, 5, 7, 4],
        [3, 8, 2, 3]],

       [[7, 3, 5, 7],
        [8, 2, 2, 7]]])

In [104]:
np.random.randint(1, 9, (3, 2, 4))

array([[[1, 4, 8, 6],
        [8, 7, 4, 8]],

       [[6, 2, 4, 2],
        [2, 4, 2, 5]],

       [[3, 6, 5, 2],
        [5, 1, 5, 1]]])

In [105]:
# rand

In [106]:
help(np.random.rand)

Help on built-in function rand:

rand(...) method of numpy.random.mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `random_sample`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, must be non-negative.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Examples
    --------
    >>> np.random.rand(3,2)
    arra

In [107]:
np.random.rand(3, 4)

array([[0.03791477, 0.51080405, 0.58778748, 0.54979159],
       [0.42632289, 0.88745576, 0.63959135, 0.31804659],
       [0.23147268, 0.92349555, 0.14562146, 0.73420361]])

In [108]:
np.random.rand(6)

array([0.0495532 , 0.14331274, 0.15872107, 0.98478397, 0.50888794,
       0.0037065 ])

In [109]:
np.random.rand(6)

array([0.76044821, 0.76543842, 0.47451973, 0.25673257, 0.23438833,
       0.79740416])

In [110]:
np.random.rand(3, 2, 3)

array([[[0.10058692, 0.07686477, 0.28140814],
        [0.23559368, 0.68316833, 0.853111  ]],

       [[0.44268114, 0.59165805, 0.2277904 ],
        [0.34534378, 0.63582524, 0.53215135]],

       [[0.48707486, 0.28427646, 0.32262651],
        [0.93201654, 0.81527641, 0.44182678]]])

In [111]:
# randn

In [112]:
help(np.random.randn)

Help on built-in function randn:

randn(...) method of numpy.random.mtrand.RandomState instance
    randn(d0, d1, ..., dn)
    
    Return a sample (or samples) from the "standard normal" distribution.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `standard_normal`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    .. note::
        New code should use the
        `~numpy.random.Generator.standard_normal`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.
    
    If positive int_like arguments are provided, `randn` generates an array
    of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1. A single float randomly sampled
    from the distribu

In [113]:
np.random.randn(3, 2)

array([[ 0.13113199,  0.01108351],
       [ 1.11320187, -0.11620217],
       [ 0.41149852,  0.417011  ]])

In [114]:
# zeros

In [115]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [116]:
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [117]:
np.zeros((3,4), dtype=np.int32)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [118]:
# ones

In [119]:
np.ones((3,4), dtype=np.int32)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [120]:
# full

In [121]:
np.full((3,4), 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [122]:
np.full((3,4), 2.0)

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [123]:
# Matrix functions

In [124]:
# identity()

In [126]:
# Identity matrix???
# It is a square matrix (no. of rows == no. of columns) whose main diagonal elements are 1 and rest of the elements are 0

In [127]:
help(np.identity)

Help on function identity in module numpy:

identity(n, dtype=None, *, like=None)
    Return the identity array.
    
    The identity array is a square array with ones on
    the main diagonal.
    
    Parameters
    ----------
    n : int
        Number of rows (and columns) in `n` x `n` output.
    dtype : data-type, optional
        Data-type of the output.  Defaults to ``float``.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. versionadded:: 1.20.0
    
    Returns
    -------
    out : ndarray
        `n` x `n` array with its main diagonal set to one,
        and all other elements 0.
    
    Examples
    --------
    >>> np.identity(3)
    

In [128]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [129]:
np.identity(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [130]:
np.identity(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [131]:
# diag

In [132]:
m1 = np.random.randint(1, 10, (4,4))

In [133]:
m1

array([[9, 6, 4, 8],
       [6, 8, 5, 4],
       [9, 4, 5, 8],
       [4, 7, 6, 2]])

In [134]:
np.diag(m1, k=0) # k is diagonal

array([9, 8, 5, 2])

In [135]:
np.diag(m1, k=1)

array([6, 5, 8])

In [136]:
np.diag(m1, k=-1)

array([6, 4, 6])

In [137]:
np.diag(m1, k=2)

array([4, 4])

In [138]:
np.diag(m1, k=-2)

array([9, 7])

In [139]:
np.diag(m1, k=3)

array([8])

In [140]:
np.diag(m1, k=-3)

array([4])

In [141]:
np.diag(m1, k=4)

array([], dtype=int32)

In [146]:
m2 = np.random.randint(0, 10, (5,))

In [147]:
m2

array([5, 9, 3, 7, 4])

In [148]:
np.diag(m2, k=0)

array([[5, 0, 0, 0, 0],
       [0, 9, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 7, 0],
       [0, 0, 0, 0, 4]])

In [149]:
help(np.diag)

Help on function diag in module numpy:

diag(v, k=0)
    Extract a diagonal or construct a diagonal array.
    
    See the more detailed documentation for ``numpy.diagonal`` if you use this
    function to extract a diagonal and wish to write to the resulting array;
    whether it returns a copy or a view depends on what version of numpy you
    are using.
    
    Parameters
    ----------
    v : array_like
        If `v` is a 2-D array, return a copy of its `k`-th diagonal.
        If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
        diagonal.
    k : int, optional
        Diagonal in question. The default is 0. Use `k>0` for diagonals
        above the main diagonal, and `k<0` for diagonals below the main
        diagonal.
    
    Returns
    -------
    out : ndarray
        The extracted diagonal or constructed diagonal array.
    
    See Also
    --------
    diagonal : Return specified diagonals.
    diagflat : Create a 2-D array with the flattened input 

In [150]:
m2

array([5, 9, 3, 7, 4])

In [151]:
np.diag(m2, k=1)

array([[0, 5, 0, 0, 0, 0],
       [0, 0, 9, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0]])

In [152]:
np.diag(m2, k=2)

array([[0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 9, 0, 0, 0],
       [0, 0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [153]:
np.diag(m2, k=-2)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [5, 0, 0, 0, 0, 0, 0],
       [0, 9, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 7, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0]])

In [155]:
# Broadcasting

In [156]:
arr1 = np.random.randint(0,9,(5,))

In [157]:
arr1

array([3, 6, 8, 5, 4])

In [160]:
arr2 = np.random.randint(0,9,(5,))

In [161]:
arr2

array([4, 0, 6, 2, 1])

In [162]:
arr1 + arr2

array([ 7,  6, 14,  7,  5])

In [163]:
arr1 - arr2

array([-1,  6,  2,  3,  3])

In [164]:
arr1 * arr2

array([12,  0, 48, 10,  4])

In [165]:
arr1

array([3, 6, 8, 5, 4])

In [166]:
arr2

array([4, 0, 6, 2, 1])

In [167]:
arr1 / arr2

C:\Users\hp\AppData\Local\Temp\ipykernel_15576\1771818627.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1 / arr2


array([0.75      ,        inf, 1.33333333, 2.5       , 4.        ])

In [169]:
arr3 = np.random.randint(0, 10, (4,))

In [170]:
arr3

array([8, 6, 8, 3])

In [171]:
arr1

array([3, 6, 8, 5, 4])

In [172]:
arr1 + arr3

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [173]:
arr1

array([3, 6, 8, 5, 4])

In [174]:
arr2

array([4, 0, 6, 2, 1])

In [175]:
arr1 > arr2

array([False,  True,  True,  True,  True])