In [1]:
# NumPy => Numerical Python
# It provides data structures/datatypes, methods/functions that can perform numericalmathematicalscientific calculations

In [2]:
# It proides a multi-dimensional array

https://numpy.org/

In [3]:
import numpy as np

In [4]:
# Numpy arrays => ndarray => n-dimensional arrays

In [5]:
arr1 = np.array([1,2,3,4,5])

In [6]:
arr1

array([1, 2, 3, 4, 5])

In [7]:
print(arr1)

[1 2 3 4 5]


In [8]:
type(arr1)

numpy.ndarray

In [9]:
# ndim => proivdes the number of dimensions of the array

In [10]:
arr1

array([1, 2, 3, 4, 5])

In [11]:
arr1.ndim

1

In [12]:
# size => returns the number of individual elements from the array

In [13]:
arr1.size

5

In [14]:
len(arr1)

5

In [15]:
# dtype => returns the datatype of individual elements

In [16]:
# Numpy arrays are homogeneous

In [17]:
arr1

array([1, 2, 3, 4, 5])

In [18]:
arr1.dtype

dtype('int32')

In [19]:
help(np.int32)

Help on class int32 in module numpy:

class int32(signedinteger)
 |  Signed integer type, compatible with Python `int` and C ``long``.
 |  
 |  :Character code: ``'l'``
 |  :Canonical name: `numpy.int_`
 |  :Alias on this platform (win32 AMD64): `numpy.int32`: 32-bit signed integer (``-2_147_483_648`` to ``2_147_483_647``).
 |  
 |  Method resolution order:
 |      int32
 |      signedinteger
 |      integer
 |      number
 |      generic
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __and__(self, value, /)
 |      Return self&value.
 |  
 |  __bool__(self, /)
 |      True if self else False
 |  
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __float__(self, /)
 |      float(self)
 |  
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |  
 |  __ge__(self, value, /)
 

In [20]:
help(np.int64)

Help on class int64 in module numpy:

class int64(signedinteger)
 |  Signed integer type, compatible with C ``long long``.
 |  
 |  :Character code: ``'q'``
 |  :Canonical name: `numpy.longlong`
 |  :Alias on this platform (win32 AMD64): `numpy.int64`: 64-bit signed integer (``-9_223_372_036_854_775_808`` to ``9_223_372_036_854_775_807``).
 |  :Alias on this platform (win32 AMD64): `numpy.intp`: Signed integer large enough to fit pointer, compatible with C ``intptr_t``.
 |  
 |  Method resolution order:
 |      int64
 |      signedinteger
 |      integer
 |      number
 |      generic
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __and__(self, value, /)
 |      Return self&value.
 |  
 |  __bool__(self, /)
 |      True if self else False
 |  
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |  
 |  __eq__(self, value, /)
 |      Return self==value

In [21]:
help(np.int8)

Help on class int8 in module numpy:

class int8(signedinteger)
 |  Signed integer type, compatible with C ``char``.
 |  
 |  :Character code: ``'b'``
 |  :Canonical name: `numpy.byte`
 |  :Alias on this platform (win32 AMD64): `numpy.int8`: 8-bit signed integer (``-128`` to ``127``).
 |  
 |  Method resolution order:
 |      int8
 |      signedinteger
 |      integer
 |      number
 |      generic
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __and__(self, value, /)
 |      Return self&value.
 |  
 |  __bool__(self, /)
 |      True if self else False
 |  
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __float__(self, /)
 |      float(self)
 |  
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __gt__

In [22]:
help(np.int16)

Help on class int16 in module numpy:

class int16(signedinteger)
 |  Signed integer type, compatible with C ``short``.
 |  
 |  :Character code: ``'h'``
 |  :Canonical name: `numpy.short`
 |  :Alias on this platform (win32 AMD64): `numpy.int16`: 16-bit signed integer (``-32_768`` to ``32_767``).
 |  
 |  Method resolution order:
 |      int16
 |      signedinteger
 |      integer
 |      number
 |      generic
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __and__(self, value, /)
 |      Return self&value.
 |  
 |  __bool__(self, /)
 |      True if self else False
 |  
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __float__(self, /)
 |      float(self)
 |  
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |

In [23]:
l1 = [1,2,3,4,5]

In [24]:
l1

[1, 2, 3, 4, 5]

In [25]:
type(l1)

list

In [26]:
arr1

array([1, 2, 3, 4, 5])

In [27]:
print(arr1)

[1 2 3 4 5]


In [28]:
c1 = 4 + 6j

In [29]:
help(c1)

Help on complex object:

class complex(object)
 |  complex(real=0, imag=0)
 |  
 |  Create a complex number from a real part and an optional imaginary part.
 |  
 |  This is equivalent to (real + imag*1j) where imag defaults to 0.
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __bool__(self, /)
 |      True if self else False
 |  
 |  __complex__(self, /)
 |      Convert this value to exact type complex.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __format__(self, format_spec, /)
 |      Convert to a string according to format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getnewargs__(self, /)
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |  __le__(self, value, /)
 |      Return self<=val