In [1]:
import numpy as np

In [2]:
# Broadcasting

In [3]:
arr1 = np.random.randint(0,9,(5,))

In [4]:
arr2 = np.random.randint(0,9,(5,))

In [5]:
arr3 = np.random.randint(0, 10, (4,))

In [6]:
arr1

array([6, 1, 6, 8, 5])

In [7]:
arr2

array([3, 6, 8, 7, 8])

In [8]:
arr3

array([6, 4, 8, 7])

In [9]:
arr1 > arr2

array([ True, False, False,  True, False])

In [10]:
arr1 > arr3

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [11]:
m1 = np.random.randint(0,9,(3,4))

In [12]:
m1

array([[5, 5, 4, 5],
       [7, 5, 8, 6],
       [3, 2, 7, 5]])

In [13]:
m2 = np.random.randint(0,9,(3,4))

In [14]:
m2

array([[1, 8, 0, 4],
       [6, 5, 2, 5],
       [8, 1, 4, 8]])

In [15]:
m1 + m2

array([[ 6, 13,  4,  9],
       [13, 10, 10, 11],
       [11,  3, 11, 13]])

In [16]:
m1 - m2

array([[ 4, -3,  4,  1],
       [ 1,  0,  6,  1],
       [-5,  1,  3, -3]])

In [17]:
m1

array([[5, 5, 4, 5],
       [7, 5, 8, 6],
       [3, 2, 7, 5]])

In [18]:
m2

array([[1, 8, 0, 4],
       [6, 5, 2, 5],
       [8, 1, 4, 8]])

In [19]:
m1 * m2

array([[ 5, 40,  0, 20],
       [42, 25, 16, 30],
       [24,  2, 28, 40]])

In [20]:
# dot product??

In [21]:
# for dot product to work, the number of cols of the first matrux should be equal to the number of rows of the second matrix

In [22]:
m1 @ m2

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [24]:
m1 = np.array([[3,1,1],
              [2,1,1]])

In [25]:
m1

array([[3, 1, 1],
       [2, 1, 1]])

In [26]:
m2 = np.array([[2, 1],
              [3, 0],
              [2,4]])

In [27]:
m2

array([[2, 1],
       [3, 0],
       [2, 4]])

In [28]:
m1 @ m2

array([[11,  7],
       [ 9,  6]])

In [29]:
m1 

array([[3, 1, 1],
       [2, 1, 1]])

In [30]:
m2

array([[2, 1],
       [3, 0],
       [2, 4]])

In [31]:
a1

NameError: name 'a1' is not defined

In [32]:
arr1

array([6, 1, 6, 8, 5])

In [33]:
arr2

array([3, 6, 8, 7, 8])

In [34]:
arr1 + arr2

array([ 9,  7, 14, 15, 13])

In [35]:
np.add(arr1, arr2)

array([ 9,  7, 14, 15, 13])

In [36]:
np.subtract(arr1, arr2)

array([ 3, -5, -2,  1, -3])

In [37]:
np.multiply(arr1, arr2)

array([18,  6, 48, 56, 40])

In [38]:
m1

array([[3, 1, 1],
       [2, 1, 1]])

In [39]:
m2

array([[2, 1],
       [3, 0],
       [2, 4]])

In [40]:
np.dot(m1, m2)

array([[11,  7],
       [ 9,  6]])

In [41]:
m1

array([[3, 1, 1],
       [2, 1, 1]])

In [42]:
np.mean(m1)

1.5

In [44]:
np.median(m1)

1.0

In [45]:
np.std(m1)

0.7637626158259734

In [46]:
np.var(m1)

0.5833333333333334

In [47]:
m1

array([[3, 1, 1],
       [2, 1, 1]])

In [48]:
np.transpose(m1)

array([[3, 2],
       [1, 1],
       [1, 1]])

In [49]:
m1.T

array([[3, 2],
       [1, 1],
       [1, 1]])

In [50]:
# Indexing and Slicing in arrays

In [51]:
arr1

array([6, 1, 6, 8, 5])

In [52]:
a1 = np.random.randint(0, 10, (10,))

In [53]:
a1

array([2, 1, 4, 6, 7, 9, 8, 5, 0, 3])

In [54]:
a1[0]

2

In [55]:
a1[-1]

3

In [56]:
a1[4:8:1]

array([7, 9, 8, 5])

In [57]:
a1[2:8:2]

array([4, 7, 8])

In [58]:
a1

array([2, 1, 4, 6, 7, 9, 8, 5, 0, 3])

In [59]:
a1[0] = 20

In [60]:
a1

array([20,  1,  4,  6,  7,  9,  8,  5,  0,  3])

In [61]:
a1[3:6]

array([6, 7, 9])

In [62]:
a1[3:6] = 10

In [63]:
a1

array([20,  1,  4, 10, 10, 10,  8,  5,  0,  3])

In [64]:
a1[3:6] = [1,2,3]

In [65]:
a1

array([20,  1,  4,  1,  2,  3,  8,  5,  0,  3])

In [66]:
a1[3:6] = [100, 200, 3000, 40]

ValueError: could not broadcast input array from shape (4,) into shape (3,)

In [67]:
a1

array([20,  1,  4,  1,  2,  3,  8,  5,  0,  3])

In [68]:
a1[3:6] = [10, 20]

ValueError: could not broadcast input array from shape (2,) into shape (3,)

In [69]:
# View

In [70]:
a1

array([20,  1,  4,  1,  2,  3,  8,  5,  0,  3])

In [71]:
slice1 = a1[3:6]

In [72]:
slice1

array([1, 2, 3])

In [73]:
slice1[0]

1

In [74]:
slice1[0] = -5

In [75]:
slice1

array([-5,  2,  3])

In [76]:
a1

array([20,  1,  4, -5,  2,  3,  8,  5,  0,  3])

In [77]:
l1 = [1,2,3,4,5,6]

In [78]:
l1

[1, 2, 3, 4, 5, 6]

In [79]:
slice2 = l1[2:4]

In [80]:
slice2

[3, 4]

In [81]:
slice2[0] = 100

In [82]:
slice2

[100, 4]

In [83]:
l1

[1, 2, 3, 4, 5, 6]

In [84]:
# Arrays creates view when sliced, lists creates a new list

In [85]:
m1

array([[3, 1, 1],
       [2, 1, 1]])

In [86]:
m3 = np.random.randint(0, 10, (3,4))

In [87]:
m3

array([[6, 2, 5, 2],
       [7, 1, 5, 2],
       [1, 6, 6, 6]])

In [88]:
m3[0]

array([6, 2, 5, 2])

In [89]:
m3[1][2]

5

In [90]:
m3[1, 2]

5

In [91]:
# array[row][col]
# array[row, col]

In [92]:
m3

array([[6, 2, 5, 2],
       [7, 1, 5, 2],
       [1, 6, 6, 6]])

In [93]:
m3[0:2]

array([[6, 2, 5, 2],
       [7, 1, 5, 2]])

In [94]:
m3[0:2, 1:3]

array([[2, 5],
       [1, 5]])

In [95]:
m3[1:3, 2:4]

array([[5, 2],
       [6, 6]])

In [97]:
m3

array([[6, 2, 5, 2],
       [7, 1, 5, 2],
       [1, 6, 6, 6]])

In [98]:
m3[0,1] = 100

In [99]:
m3

array([[  6, 100,   5,   2],
       [  7,   1,   5,   2],
       [  1,   6,   6,   6]])

In [96]:
# linspace

In [100]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

In [101]:
np.linspace(1, 50)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [102]:
# Arithmetic progression -> even spaced sequence

In [103]:
np.linspace(1, 20, 10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [ ]:
# a(n) = a+ (n-1)d
# a -> first values
# d -> common diff
# n -> 10

In [104]:
# geomspace

In [105]:
help(np.geomspace)

Help on function geomspace in module numpy:

geomspace(start, stop, num=50, endpoint=True, dtype=None, axis=0)
    Return numbers spaced evenly on a log scale (a geometric progression).
    
    This is similar to `logspace`, but with endpoints specified directly.
    Each output sample is a constant multiple of the previous.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The final value of the sequence, unless `endpoint` is False.
        In that case, ``num + 1`` values are spaced over the
        interval in log-space, of which all but the last (a sequence of
        length `num`) are returned.
    num : integer, optional
        Number of samples to generate.  Default is 50.
    endpoint : boolean, optional
        If true, `stop` is the last sample. Otherwise, it is not included.
        Default is True.
 

In [106]:
np.geomspace(1, 20, 10)

array([ 1.        ,  1.39495079,  1.94588772,  2.71441762,  3.78647901,
        5.2819519 ,  7.368063  , 10.27808533, 14.33742329, 20.        ])

In [107]:
1.39495079 / 1

1.39495079

In [108]:
1.94588772 / 1.39495079

1.394950799662259

In [109]:
14.33742329 / 10.27808533

1.3949507938167702

In [111]:
type(1.3949507938167702)

float

In [110]:
# all() and any()

In [112]:
arr1 = np.random.randint(0, 10, (3,3))

In [113]:
arr1

array([[8, 8, 8],
       [2, 3, 2],
       [6, 6, 3]])

In [114]:
np.all(arr1)

True

In [115]:
arr2 = np.random.randint(0, 10, (3,3))

In [116]:
arr2

array([[7, 4, 3],
       [1, 4, 3],
       [0, 1, 8]])

In [117]:
np.all(arr2)

False

In [119]:
arr1

array([[8, 8, 8],
       [2, 3, 2],
       [6, 6, 3]])

In [118]:
np.any(arr1)

True

In [120]:
arr2

array([[7, 4, 3],
       [1, 4, 3],
       [0, 1, 8]])

In [121]:
np.any(arr2)

True

In [122]:
arr3 = np.array([[0,0],
                [0,0]])

In [123]:
arr3

array([[0, 0],
       [0, 0]])

In [124]:
np.any(arr3)

False

In [125]:
help(np.all)

Help on function all in module numpy:

all(a, axis=None, out=None, keepdims=<no value>, *, where=<no value>)
    Test whether all array elements along a given axis evaluate to True.
    
    Parameters
    ----------
    a : array_like
        Input array or object that can be converted to an array.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a logical AND reduction is performed.
        The default (``axis=None``) is to perform a logical AND over all
        the dimensions of the input array. `axis` may be negative, in
        which case it counts from the last to the first axis.
    
        .. versionadded:: 1.7.0
    
        If this is a tuple of ints, a reduction is performed on multiple
        axes, instead of a single axis or all the axes as before.
    out : ndarray, optional
        Alternate output array in which to place the result.
        It must have the same shape as the expected output and its
        type is preserved (e.g., if 

In [126]:
help(np.any)

Help on function any in module numpy:

any(a, axis=None, out=None, keepdims=<no value>, *, where=<no value>)
    Test whether any array element along a given axis evaluates to True.
    
    Returns single boolean if `axis` is ``None``
    
    Parameters
    ----------
    a : array_like
        Input array or object that can be converted to an array.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a logical OR reduction is performed.
        The default (``axis=None``) is to perform a logical OR over all
        the dimensions of the input array. `axis` may be negative, in
        which case it counts from the last to the first axis.
    
        .. versionadded:: 1.7.0
    
        If this is a tuple of ints, a reduction is performed on multiple
        axes, instead of a single axis or all the axes as before.
    out : ndarray, optional
        Alternate output array in which to place the result.  It must have
        the same shape as the expecte

In [128]:
arr2

array([[7, 4, 3],
       [1, 4, 3],
       [0, 1, 8]])

In [130]:
np.all(arr2, axis=0)

array([False,  True,  True])

In [131]:
np.all(arr2, axis=1)

array([ True,  True, False])

In [132]:
arr2

array([[7, 4, 3],
       [1, 4, 3],
       [0, 1, 8]])

In [133]:
np.any(arr2, axis=0)

array([ True,  True,  True])

In [134]:
np.any(arr2, axis=1)

array([ True,  True,  True])

In [135]:
arr4 = np.array([[1, 9, 3],
                [2,3,9],
                [0, 0, 0]])

In [136]:
arr4

array([[1, 9, 3],
       [2, 3, 9],
       [0, 0, 0]])

In [137]:
np.any(arr4, axis=1)

array([ True,  True, False])

In [138]:
m1

array([[3, 1, 1],
       [2, 1, 1]])

In [139]:
m3

array([[  6, 100,   5,   2],
       [  7,   1,   5,   2],
       [  1,   6,   6,   6]])

In [140]:
# Reshaping of arrays

In [141]:
m3.shape

(3, 4)

In [142]:
m3.size

12

In [143]:
np.reshape(m3, (4, 3))

array([[  6, 100,   5],
       [  2,   7,   1],
       [  5,   2,   1],
       [  6,   6,   6]])

In [144]:
np.reshape(m3, (3, 3))

ValueError: cannot reshape array of size 12 into shape (3,3)

In [145]:
# For reshaping, the input array and the output should have the same size!!

In [146]:
m3

array([[  6, 100,   5,   2],
       [  7,   1,   5,   2],
       [  1,   6,   6,   6]])

In [147]:
np.reshape(m3, (6, 2))

array([[  6, 100],
       [  5,   2],
       [  7,   1],
       [  5,   2],
       [  1,   6],
       [  6,   6]])

In [148]:
m3

array([[  6, 100,   5,   2],
       [  7,   1,   5,   2],
       [  1,   6,   6,   6]])

In [149]:
np.reshape(m3, (12,))

array([  6, 100,   5,   2,   7,   1,   5,   2,   1,   6,   6,   6])

In [150]:
np.reshape(m3, (2, 3, 2))

array([[[  6, 100],
        [  5,   2],
        [  7,   1]],

       [[  5,   2],
        [  1,   6],
        [  6,   6]]])