In [1]:
import pandas as pd

In [2]:
# Sorting series

In [5]:
sub1 = pd.Series([77.0, 81.0, 89.5, 91.0, 65.5], index=['Mark', 'Carol', 'John', 'Jill', 'Dan'], name='English')

In [6]:
sub1

Mark     77.0
Carol    81.0
John     89.5
Jill     91.0
Dan      65.5
Name: English, dtype: float64

In [7]:
sub1.sort_index()

Carol    81.0
Dan      65.5
Jill     91.0
John     89.5
Mark     77.0
Name: English, dtype: float64

In [8]:
sub1.sort_index(ascending=False)

Mark     77.0
John     89.5
Jill     91.0
Dan      65.5
Carol    81.0
Name: English, dtype: float64

In [9]:
sub1

Mark     77.0
Carol    81.0
John     89.5
Jill     91.0
Dan      65.5
Name: English, dtype: float64

In [10]:
sub1.sort_index(ascending=False, inplace=True)

In [11]:
sub1

Mark     77.0
John     89.5
Jill     91.0
Dan      65.5
Carol    81.0
Name: English, dtype: float64

In [12]:
sub1.sort_values()

Dan      65.5
Mark     77.0
Carol    81.0
John     89.5
Jill     91.0
Name: English, dtype: float64

In [13]:
sub1.sort_values(ascending=False)

Jill     91.0
John     89.5
Carol    81.0
Mark     77.0
Dan      65.5
Name: English, dtype: float64

In [14]:
sub1

Mark     77.0
John     89.5
Jill     91.0
Dan      65.5
Carol    81.0
Name: English, dtype: float64

In [15]:
sub1.sort_values(ascending=False, inplace=True)

In [16]:
sub1

Jill     91.0
John     89.5
Carol    81.0
Mark     77.0
Dan      65.5
Name: English, dtype: float64

In [17]:
help(sub1.sort_values)

Help on method sort_values in module pandas.core.series:

sort_values(*, axis: 'Axis' = 0, ascending: 'bool | int | Sequence[bool] | Sequence[int]' = True, inplace: 'bool' = False, kind: 'str' = 'quicksort', na_position: 'str' = 'last', ignore_index: 'bool' = False, key: 'ValueKeyFunc' = None) -> 'Series | None' method of pandas.core.series.Series instance
    Sort by the values.
    
    Sort a Series in ascending or descending order by some
    criterion.
    
    Parameters
    ----------
    axis : {0 or 'index'}
        Unused. Parameter needed for compatibility with DataFrame.
    ascending : bool or list of bools, default True
        If True, sort values in ascending order, otherwise descending.
    inplace : bool, default False
        If True, perform operation in-place.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, default 'quicksort'
        Choice of sorting algorithm. See also :func:`numpy.sort` for more
        information. 'mergesort' and 'stable' are the

In [18]:
help(sub1.sort_index)

Help on method sort_index in module pandas.core.series:

sort_index(*, axis: 'Axis' = 0, level: 'IndexLabel' = None, ascending: 'bool | Sequence[bool]' = True, inplace: 'bool' = False, kind: 'SortKind' = 'quicksort', na_position: 'NaPosition' = 'last', sort_remaining: 'bool' = True, ignore_index: 'bool' = False, key: 'IndexKeyFunc' = None) -> 'Series | None' method of pandas.core.series.Series instance
    Sort Series by index labels.
    
    Returns a new Series sorted by label if `inplace` argument is
    ``False``, otherwise updates the original series and returns None.
    
    Parameters
    ----------
    axis : {0 or 'index'}
        Unused. Parameter needed for compatibility with DataFrame.
    level : int, optional
        If not None, sort on values in specified index level(s).
    ascending : bool or list-like of bools, default True
        Sort ascending vs. descending. When the index is a MultiIndex the
        sort direction can be controlled for each level individually.

In [19]:
# Dataframe - 2D structure

In [20]:
data = {'ids': [111, 222, 333, 444],
       'names': ['John', 'Alice', 'Jill', 'Dan'],
       'percents': [87.5, 78.5, 91.0, 68.0]}

In [21]:
data

{'ids': [111, 222, 333, 444],
 'names': ['John', 'Alice', 'Jill', 'Dan'],
 'percents': [87.5, 78.5, 91.0, 68.0]}

In [22]:
df1 = pd.DataFrame(data)

In [23]:
print(df1)

   ids  names  percents
0  111   John      87.5
1  222  Alice      78.5
2  333   Jill      91.0
3  444    Dan      68.0


In [24]:
df1

ids  names  percents
0  111   John      87.5
1  222  Alice      78.5
2  333   Jill      91.0
3  444    Dan      68.0

In [25]:
data1 = {'ids': [111, 222, 333, 444],
       'names': ['John', 'Alice', 'Jill', 'Dan'],
       'percents': [87.5, 78.5, 91.0]}

In [26]:
df2 = pd.DataFrame(data1)

ValueError: All arrays must be of the same length

In [27]:
data1 = {'ids': [111, 222, 333, 444],
       'names': ['John', 'Alice', 'Jill', 'Dan'],
       'percents': [87.5, 78.5, 91.0, None]}

In [28]:
df2 = pd.DataFrame(data1)

In [29]:
df2

ids  names  percents
0  111   John      87.5
1  222  Alice      78.5
2  333   Jill      91.0
3  444    Dan       NaN

In [30]:
df1

ids  names  percents
0  111   John      87.5
1  222  Alice      78.5
2  333   Jill      91.0
3  444    Dan      68.0

In [31]:
type(df1)

pandas.core.frame.DataFrame

In [32]:
df1.index

RangeIndex(start=0, stop=4, step=1)

In [33]:
df1.values

array([[111, 'John', 87.5],
       [222, 'Alice', 78.5],
       [333, 'Jill', 91.0],
       [444, 'Dan', 68.0]], dtype=object)

In [34]:
df1.columns

Index(['ids', 'names', 'percents'], dtype='object')

In [35]:
v1 = df1.values

In [36]:
v1

array([[111, 'John', 87.5],
       [222, 'Alice', 78.5],
       [333, 'Jill', 91.0],
       [444, 'Dan', 68.0]], dtype=object)

In [37]:
type(v1)

numpy.ndarray

In [38]:
v1.ndim

2

In [40]:
df1 = pd.DataFrame(data, index=['a', 'b', 'c', 'd'])

In [41]:
df1

ids  names  percents
a  111   John      87.5
b  222  Alice      78.5
c  333   Jill      91.0
d  444    Dan      68.0

In [42]:
df1.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [43]:
data

{'ids': [111, 222, 333, 444],
 'names': ['John', 'Alice', 'Jill', 'Dan'],
 'percents': [87.5, 78.5, 91.0, 68.0]}

In [44]:
df1 = pd.DataFrame(data, index=['a', 'b', 'c', 'd'], columns=['names', 'ids', 'percents'])

In [45]:
df1

names  ids  percents
a   John  111      87.5
b  Alice  222      78.5
c   Jill  333      91.0
d    Dan  444      68.0

In [46]:
df3 = pd.DataFrame(data, index=['a', 'b', 'c', 'd'], columns=['ids', 'percents'])

In [47]:
df3

ids  percents
a  111      87.5
b  222      78.5
c  333      91.0
d  444      68.0

In [48]:
df1

names  ids  percents
a   John  111      87.5
b  Alice  222      78.5
c   Jill  333      91.0
d    Dan  444      68.0

In [49]:
data

{'ids': [111, 222, 333, 444],
 'names': ['John', 'Alice', 'Jill', 'Dan'],
 'percents': [87.5, 78.5, 91.0, 68.0]}

In [50]:
df1


names  ids  percents
a   John  111      87.5
b  Alice  222      78.5
c   Jill  333      91.0
d    Dan  444      68.0

In [51]:
df1.set_index('ids')

names  percents
ids                 
111   John      87.5
222  Alice      78.5
333   Jill      91.0
444    Dan      68.0

In [52]:
df4 = df1.set_index('ids')

In [53]:
df4

names  percents
ids                 
111   John      87.5
222  Alice      78.5
333   Jill      91.0
444    Dan      68.0

In [54]:
df4.index

Int64Index([111, 222, 333, 444], dtype='int64', name='ids')

In [55]:
df4.columns

Index(['names', 'percents'], dtype='object')

In [56]:
df1

names  ids  percents
a   John  111      87.5
b  Alice  222      78.5
c   Jill  333      91.0
d    Dan  444      68.0

In [57]:
df1[0]

KeyError: 0

In [58]:
df1.iloc[0]

names       John
ids          111
percents    87.5
Name: a, dtype: object

In [59]:
df1

names  ids  percents
a   John  111      87.5
b  Alice  222      78.5
c   Jill  333      91.0
d    Dan  444      68.0

In [60]:
df1.loc['a']

names       John
ids          111
percents    87.5
Name: a, dtype: object

In [61]:
df1['percents']

a    87.5
b    78.5
c    91.0
d    68.0
Name: percents, dtype: float64

In [62]:
data

{'ids': [111, 222, 333, 444],
 'names': ['John', 'Alice', 'Jill', 'Dan'],
 'percents': [87.5, 78.5, 91.0, 68.0]}

In [63]:
df5 = pd.DataFrame(data, columns=['ids', 'percents', 'grades'])

In [64]:
df5

ids  percents grades
0  111      87.5    NaN
1  222      78.5    NaN
2  333      91.0    NaN
3  444      68.0    NaN

In [65]:
df1

names  ids  percents
a   John  111      87.5
b  Alice  222      78.5
c   Jill  333      91.0
d    Dan  444      68.0

In [66]:
df1[2,3]

KeyError: (2, 3)

In [67]:
df1['c', 'percents']

KeyError: ('c', 'percents')

In [68]:
df1

names  ids  percents
a   John  111      87.5
b  Alice  222      78.5
c   Jill  333      91.0
d    Dan  444      68.0

In [69]:
df1['percents']

a    87.5
b    78.5
c    91.0
d    68.0
Name: percents, dtype: float64

In [70]:
df1['percents'].loc['c']

91.0

In [71]:
df1['percents'].iloc[2]

91.0

In [72]:
df1

names  ids  percents
a   John  111      87.5
b  Alice  222      78.5
c   Jill  333      91.0
d    Dan  444      68.0

In [73]:
df1.loc['c']

names       Jill
ids          333
percents    91.0
Name: c, dtype: object

In [74]:
df1.loc['c'].loc['percents']

91.0

In [75]:
df1.loc['c']['percents']

91.0

In [76]:
df1

names  ids  percents
a   John  111      87.5
b  Alice  222      78.5
c   Jill  333      91.0
d    Dan  444      68.0

In [77]:
df1.loc['c', 'percents']

91.0

In [78]:
df1.loc['c', 'percents'] = 91.5

In [79]:
df1

names  ids  percents
a   John  111      87.5
b  Alice  222      78.5
c   Jill  333      91.5
d    Dan  444      68.0

In [80]:
# deleting rows/cols

In [81]:
df5

ids  percents grades
0  111      87.5    NaN
1  222      78.5    NaN
2  333      91.0    NaN
3  444      68.0    NaN

In [82]:
df5.drop(['grades'])

KeyError: "['grades'] not found in axis"

In [83]:
help(df5.drop)

Help on method drop in module pandas.core.frame:

drop(labels: 'IndexLabel' = None, *, axis: 'Axis' = 0, index: 'IndexLabel' = None, columns: 'IndexLabel' = None, level: 'Level' = None, inplace: 'bool' = False, errors: 'IgnoreRaise' = 'raise') -> 'DataFrame | None' method of pandas.core.frame.DataFrame instance
    Drop specified labels from rows or columns.
    
    Remove rows or columns by specifying label names and corresponding
    axis, or by specifying directly index or column names. When using a
    multi-index, labels on different levels can be removed by specifying
    the level. See the `user guide <advanced.shown_levels>`
    for more information about the now unused levels.
    
    Parameters
    ----------
    labels : single label or list-like
        Index or column labels to drop. A tuple will be used as a single
        label and not treated as a list-like.
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Whether to drop labels from the index (0 or 'index

In [84]:
df5.drop(['grades'], axis=1)

ids  percents
0  111      87.5
1  222      78.5
2  333      91.0
3  444      68.0

In [85]:
df5

ids  percents grades
0  111      87.5    NaN
1  222      78.5    NaN
2  333      91.0    NaN
3  444      68.0    NaN

In [86]:
df5.drop(['grades'], axis=1, inplace=True)

In [87]:
df5

ids  percents
0  111      87.5
1  222      78.5
2  333      91.0
3  444      68.0

In [88]:
df2

ids  names  percents
0  111   John      87.5
1  222  Alice      78.5
2  333   Jill      91.0
3  444    Dan       NaN

In [89]:
df2.drop([1, 3], axis=0, inplace=True)

In [90]:
df2

ids names  percents
0  111  John      87.5
2  333  Jill      91.0

In [91]:
df1

names  ids  percents
a   John  111      87.5
b  Alice  222      78.5
c   Jill  333      91.5
d    Dan  444      68.0

In [92]:
help(df1.to_excel)

Help on method to_excel in module pandas.core.generic:

to_excel(excel_writer, sheet_name: 'str' = 'Sheet1', na_rep: 'str' = '', float_format: 'str | None' = None, columns: 'Sequence[Hashable] | None' = None, header: 'Sequence[Hashable] | bool_t' = True, index: 'bool_t' = True, index_label: 'IndexLabel' = None, startrow: 'int' = 0, startcol: 'int' = 0, engine: 'str | None' = None, merge_cells: 'bool_t' = True, encoding: 'lib.NoDefault' = <no_default>, inf_rep: 'str' = 'inf', verbose: 'lib.NoDefault' = <no_default>, freeze_panes: 'tuple[int, int] | None' = None, storage_options: 'StorageOptions' = None) -> 'None' method of pandas.core.frame.DataFrame instance
    Write object to an Excel sheet.
    
    To write a single object to an Excel .xlsx file it is only necessary to
    specify a target file name. To write to multiple sheets it is necessary to
    create an `ExcelWriter` object with a target file name, and specify a sheet
    in the file to write to.
    
    Multiple sheets may

In [93]:
# Creating / changing cols

In [94]:
df1

names  ids  percents
a   John  111      87.5
b  Alice  222      78.5
c   Jill  333      91.5
d    Dan  444      68.0

In [95]:
df1['col1'] = 10

In [96]:
df1

names  ids  percents  col1
a   John  111      87.5    10
b  Alice  222      78.5    10
c   Jill  333      91.5    10
d    Dan  444      68.0    10

In [97]:
import numpy as np

In [98]:
df1['col1'] = np.nan

In [99]:
df1

names  ids  percents  col1
a   John  111      87.5   NaN
b  Alice  222      78.5   NaN
c   Jill  333      91.5   NaN
d    Dan  444      68.0   NaN

In [100]:
df1['col2'] = 1,2,3,4

In [101]:
df1

names  ids  percents  col1  col2
a   John  111      87.5   NaN     1
b  Alice  222      78.5   NaN     2
c   Jill  333      91.5   NaN     3
d    Dan  444      68.0   NaN     4

In [102]:
df1['col3'] = [1,2,3,4]

In [103]:
df1

names  ids  percents  col1  col2  col3
a   John  111      87.5   NaN     1     1
b  Alice  222      78.5   NaN     2     2
c   Jill  333      91.5   NaN     3     3
d    Dan  444      68.0   NaN     4     4

In [109]:
df1['col4'] = range(10, 20, 3)

In [105]:
df1

names  ids  percents  col1  col2  col3  col4
a   John  111      87.5   NaN     1     1    10
b  Alice  222      78.5   NaN     2     2    13
c   Jill  333      91.5   NaN     3     3    16
d    Dan  444      68.0   NaN     4     4    19

In [106]:
df1['col4'] = range(10, 20, 2)

ValueError: Length of values (5) does not match length of index (4)

In [110]:
df1['col5'] = np.random.randint(1, 10, (4,))

In [111]:
df1

names  ids  percents  col1  col2  col3  col4  col5
a   John  111      87.5   NaN     1     1    10     3
b  Alice  222      78.5   NaN     2     2    13     9
c   Jill  333      91.5   NaN     3     3    16     5
d    Dan  444      68.0   NaN     4     4    19     8

In [112]:
s1 = pd.Series([8, 4, 2, 1, 8, 3, 2], index=['x', 'd', 'e', 'z', 'a', 'r', 'k'])

In [113]:
s1

x    8
d    4
e    2
z    1
a    8
r    3
k    2
dtype: int64

In [114]:
df1['col6'] = s1

In [115]:
df1

names  ids  percents  col1  col2  col3  col4  col5  col6
a   John  111      87.5   NaN     1     1    10     3   8.0
b  Alice  222      78.5   NaN     2     2    13     9   NaN
c   Jill  333      91.5   NaN     3     3    16     5   NaN
d    Dan  444      68.0   NaN     4     4    19     8   4.0

In [116]:
# Delete the columns - col1, col2, col3, col5, col6 permanently

In [117]:
df1.drop(['col1', 'col2', 'col3', 'col4', 'col5', 'col6'], inplace=True)

KeyError: "['col1', 'col2', 'col3', 'col4', 'col5', 'col6'] not found in axis"

In [118]:
df1.drop(['col1', 'col2', 'col3', 'col4', 'col5', 'col6'], inplace=True, axis=1)

In [119]:
df1

names  ids  percents
a   John  111      87.5
b  Alice  222      78.5
c   Jill  333      91.5
d    Dan  444      68.0

In [120]:
# Create a column - 'award'
# The value of award depends on the percent column
# if percent is more than 90, value will be True, else False

In [121]:
df1['percents']

a    87.5
b    78.5
c    91.5
d    68.0
Name: percents, dtype: float64

In [122]:
df1['percents'] > 90

a    False
b    False
c     True
d    False
Name: percents, dtype: bool

In [123]:
df1['award'] = df1['percents'] > 90

In [124]:
df1

names  ids  percents  award
a   John  111      87.5  False
b  Alice  222      78.5  False
c   Jill  333      91.5   True
d    Dan  444      68.0  False

In [125]:
# Create/Change a column - 'award'
# The value of award depends on the percent column
# if percent is more than 90, value will be 'Yes', else 'No'

In [126]:
# map

In [127]:
df1['award'].map({True:'Yes', False:'No'})

a     No
b     No
c    Yes
d     No
Name: award, dtype: object

In [128]:
df1['award'] = df1['award'].map({True:'Yes', False:'No'})

In [129]:
df1

names  ids  percents award
a   John  111      87.5    No
b  Alice  222      78.5    No
c   Jill  333      91.5   Yes
d    Dan  444      68.0    No

In [130]:
# Without using map

In [131]:
df1.drop(['award'], axis=1, inplace=True)

In [132]:
df1

names  ids  percents
a   John  111      87.5
b  Alice  222      78.5
c   Jill  333      91.5
d    Dan  444      68.0

In [133]:
'Yes' if percent > 90 else 'No'

NameError: name 'percent' is not defined

In [134]:
'Yes' if df1['percents'] > 90 else 'No'

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [135]:
# np.where

In [136]:
arr1 = np.random.randint(-10, 10, (5,))

In [137]:
arr1

array([-2,  4,  9, -6,  5])

In [138]:
# If the element is negative, add 2 to it
# If the element is positive, multiply it by 2

In [139]:
help(np.where)

Help on function where in module numpy:

where(...)
    where(condition, [x, y], /)
    
    Return elements chosen from `x` or `y` depending on `condition`.
    
    .. note::
        When only `condition` is provided, this function is a shorthand for
        ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
        preferred, as it behaves correctly for subclasses. The rest of this
        documentation covers only the case where all three arguments are
        provided.
    
    Parameters
    ----------
    condition : array_like, bool
        Where True, yield `x`, otherwise yield `y`.
    x, y : array_like
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.
    
    Returns
    -------
    out : ndarray
        An array with elements from `x` where `condition` is True, and elements
        from `y` elsewhere.
    
    See Also
    --------
    choose
    nonzero : The function that is called when x an

In [140]:
arr1

array([-2,  4,  9, -6,  5])

In [141]:
np.where(arr1 < 0, arr1 + 2, arr1 * 2)

array([ 0,  8, 18, -4, 10])

In [142]:
df1['percents']

a    87.5
b    78.5
c    91.5
d    68.0
Name: percents, dtype: float64

In [143]:
per = df1['percents'].values

In [144]:
per

array([87.5, 78.5, 91.5, 68. ])

In [145]:
np.where(per > 90, 'Yes', 'No')

array(['No', 'No', 'Yes', 'No'], dtype='<U3')

In [146]:
df1

names  ids  percents
a   John  111      87.5
b  Alice  222      78.5
c   Jill  333      91.5
d    Dan  444      68.0

In [147]:
df1['percents']

a    87.5
b    78.5
c    91.5
d    68.0
Name: percents, dtype: float64

In [148]:
df1['awards'] = np.where(df1['percents'] > 90, 'Yes', 'No')

In [149]:
df1

names  ids  percents awards
a   John  111      87.5     No
b  Alice  222      78.5     No
c   Jill  333      91.5    Yes
d    Dan  444      68.0     No

In [150]:
# create a column - grades
# the values of the column depends on the percent column
# if percent >= 90, grade - 'A'
# if percent between 80 and 90 (excluded), grade - 'B'
# if percent between 70 and 80 (excluded), grade - 'C'
# if percent between 60 and 70 (excluded), grade - 'D'
# if percent < 60, grade - 'F'

In [151]:
# apply

In [153]:
help(df1.apply)

Help on method apply in module pandas.core.frame:

apply(func: 'AggFuncType', axis: 'Axis' = 0, raw: 'bool' = False, result_type: "Literal['expand', 'reduce', 'broadcast'] | None" = None, args=(), **kwargs) method of pandas.core.frame.DataFrame instance
    Apply a function along an axis of the DataFrame.
    
    Objects passed to the function are Series objects whose index is
    either the DataFrame's index (``axis=0``) or the DataFrame's columns
    (``axis=1``). By default (``result_type=None``), the final return type
    is inferred from the return type of the applied function. Otherwise,
    it depends on the `result_type` argument.
    
    Parameters
    ----------
    func : function
        Function to apply to each column or row.
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Axis along which the function is applied:
    
        * 0 or 'index': apply function to each column.
        * 1 or 'columns': apply function to each row.
    
    raw : bool, default Fa

In [154]:
help(df1['percents'].apply)

Help on method apply in module pandas.core.series:

apply(func: 'AggFuncType', convert_dtype: 'bool' = True, args: 'tuple[Any, ...]' = (), **kwargs) -> 'DataFrame | Series' method of pandas.core.series.Series instance
    Invoke function on values of Series.
    
    Can be ufunc (a NumPy function that applies to the entire Series)
    or a Python function that only works on single values.
    
    Parameters
    ----------
    func : function
        Python function or NumPy ufunc to apply.
    convert_dtype : bool, default True
        Try to find better dtype for elementwise function results. If
        False, leave as dtype=object. Note that the dtype is always
        preserved for some extension array dtypes, such as Categorical.
    args : tuple
        Positional arguments passed to func after the series value.
    **kwargs
        Additional keyword arguments passed to func.
    
    Returns
    -------
    Series or DataFrame
        If func returns a Series object the result

In [155]:
def get_grade(percent):
    if percent >= 90:
        return 'A'
    elif percent >= 80 and percent < 90:
        return 'B'
    elif percent >= 70 and percent < 80:
        return 'C'
    elif percent >= 60 and percent < 70:
        return 'D'
    else:
        return 'F'

In [156]:
get_grade(61)

'D'

In [157]:
get_grade(91)

'A'

In [158]:
df1

names  ids  percents awards
a   John  111      87.5     No
b  Alice  222      78.5     No
c   Jill  333      91.5    Yes
d    Dan  444      68.0     No

In [159]:
df1['percents'].apply(get_grade)

a    B
b    C
c    A
d    D
Name: percents, dtype: object

In [160]:
df1['grades'] = df1['percents'].apply(get_grade)

In [161]:
df1

names  ids  percents awards grades
a   John  111      87.5     No      B
b  Alice  222      78.5     No      C
c   Jill  333      91.5    Yes      A
d    Dan  444      68.0     No      D

In [162]:
# Read an excel as a dataframe

In [163]:
shares_df = pd.read_excel('share_example.xlsx')

In [164]:
shares_df

Date    A  B    C   D     E
0 2022-01-20   99  20  45  56  2000
1 2022-01-21   98  19  47  55  1993
2 2022-01-22   95  19  50  60  1921
3 2022-01-23  101  22  56  61  1976
4 2022-01-24  103  22  55  65  2010

In [165]:
shares_df.index

RangeIndex(start=0, stop=5, step=1)

In [166]:
shares_df.columns

Index(['Date', 'A', 'B ', 'C', 'D', 'E'], dtype='object')

In [167]:
shares_df.values

array([[Timestamp('2022-01-20 00:00:00'), 99, 20, 45, 56, 2000],
       [Timestamp('2022-01-21 00:00:00'), 98, 19, 47, 55, 1993],
       [Timestamp('2022-01-22 00:00:00'), 95, 19, 50, 60, 1921],
       [Timestamp('2022-01-23 00:00:00'), 101, 22, 56, 61, 1976],
       [Timestamp('2022-01-24 00:00:00'), 103, 22, 55, 65, 2010]],
      dtype=object)

In [168]:
shares_df

Date    A  B    C   D     E
0 2022-01-20   99  20  45  56  2000
1 2022-01-21   98  19  47  55  1993
2 2022-01-22   95  19  50  60  1921
3 2022-01-23  101  22  56  61  1976
4 2022-01-24  103  22  55  65  2010

In [169]:
shares_df['Date']

0   2022-01-20
1   2022-01-21
2   2022-01-22
3   2022-01-23
4   2022-01-24
Name: Date, dtype: datetime64[ns]

In [170]:
shares_df['Date'].loc[0]

Timestamp('2022-01-20 00:00:00')

In [171]:
type(shares_df['Date'].loc[0])

pandas._libs.tslibs.timestamps.Timestamp

In [172]:
shares_df

Date    A  B    C   D     E
0 2022-01-20   99  20  45  56  2000
1 2022-01-21   98  19  47  55  1993
2 2022-01-22   95  19  50  60  1921
3 2022-01-23  101  22  56  61  1976
4 2022-01-24  103  22  55  65  2010

In [173]:
shares_df['F'] = 50, 54, 51, 49, 46

In [174]:
shares_df

Date    A  B    C   D     E   F
0 2022-01-20   99  20  45  56  2000  50
1 2022-01-21   98  19  47  55  1993  54
2 2022-01-22   95  19  50  60  1921  51
3 2022-01-23  101  22  56  61  1976  49
4 2022-01-24  103  22  55  65  2010  46

In [175]:
shares_df.to_excel('shares_new.xlsx')

In [176]:
shares_df.to_excel('shares_new_1.xlsx', index=False)

In [177]:
shares_df

Date    A  B    C   D     E   F
0 2022-01-20   99  20  45  56  2000  50
1 2022-01-21   98  19  47  55  1993  54
2 2022-01-22   95  19  50  60  1921  51
3 2022-01-23  101  22  56  61  1976  49
4 2022-01-24  103  22  55  65  2010  46

In [178]:
# Stacking

In [179]:
df1

names  ids  percents awards grades
a   John  111      87.5     No      B
b  Alice  222      78.5     No      C
c   Jill  333      91.5    Yes      A
d    Dan  444      68.0     No      D

In [180]:
stacked_df1 = df1.stack()

In [181]:
stacked_df1

a  names        John
   ids           111
   percents     87.5
   awards         No
   grades          B
b  names       Alice
   ids           222
   percents     78.5
   awards         No
   grades          C
c  names        Jill
   ids           333
   percents     91.5
   awards        Yes
   grades          A
d  names         Dan
   ids           444
   percents     68.0
   awards         No
   grades          D
dtype: object

In [182]:
type(stacked_df1)

pandas.core.series.Series

In [183]:
stacked_df1.values

array(['John', 111, 87.5, 'No', 'B', 'Alice', 222, 78.5, 'No', 'C',
       'Jill', 333, 91.5, 'Yes', 'A', 'Dan', 444, 68.0, 'No', 'D'],
      dtype=object)

In [184]:
stacked_df1.index

MultiIndex([('a',    'names'),
            ('a',      'ids'),
            ('a', 'percents'),
            ('a',   'awards'),
            ('a',   'grades'),
            ('b',    'names'),
            ('b',      'ids'),
            ('b', 'percents'),
            ('b',   'awards'),
            ('b',   'grades'),
            ('c',    'names'),
            ('c',      'ids'),
            ('c', 'percents'),
            ('c',   'awards'),
            ('c',   'grades'),
            ('d',    'names'),
            ('d',      'ids'),
            ('d', 'percents'),
            ('d',   'awards'),
            ('d',   'grades')],
           )

In [185]:
stacked_df1.loc[('c', 'ids')]

333

In [187]:
df1

names  ids  percents awards grades
a   John  111      87.5     No      B
b  Alice  222      78.5     No      C
c   Jill  333      91.5    Yes      A
d    Dan  444      68.0     No      D

In [188]:
# Fetch the percent of 'Jill'

In [189]:
df1['percents'].loc['c']

91.5

In [191]:
stacked_df1.loc[('c', 'percents')]

91.5

In [192]:
stacked_df1

a  names        John
   ids           111
   percents     87.5
   awards         No
   grades          B
b  names       Alice
   ids           222
   percents     78.5
   awards         No
   grades          C
c  names        Jill
   ids           333
   percents     91.5
   awards        Yes
   grades          A
d  names         Dan
   ids           444
   percents     68.0
   awards         No
   grades          D
dtype: object

In [193]:
stacked_df1.unstack()

names  ids percents awards grades
a   John  111     87.5     No      B
b  Alice  222     78.5     No      C
c   Jill  333     91.5    Yes      A
d    Dan  444     68.0     No      D